# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install system libs
        run: |
          sudo apt-get update;
          sudo apt-get install --no-install-recommends -y curl build-essential;
      - name: Install poetry
        run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      
      - name: install robot framework
        run: pip install robotframework
      # Runs a set of commands using the runners shell
      - name: Run robot pipeline
        run: robot .
